# トレーディングパラメータ
trading_params:
  # 取引対象の通貨ペア一覧
  symbols:
    - BTCUSDT
    # - ETHUSDT
    # - ASTERUSDT
    # - SOLUSDT

  # 並列トレードモード（複数ウォレットペアで同時に取引）
  # 複雑になるため現在は無効化
  # parallel_trading_enabled: false

  # シンボルごとのポジションサイズ（USDT建て）
  # 各シンボルで異なるサイズを設定可能
  position_sizes:
    BTCUSDT: 5000      
    ETHUSDT: 2000      
    ASTERUSDT: 1000   
    # SOLUSDT: 100      

  # デフォルトポジションサイズ（上記で指定されていないシンボル用）
  default_position_size_usdt: 500

  # ポジションサイズの変動幅（0.05 = 5%のランダム変動）
  position_size_variance: 0.3

  # 最小ポジション保有時間（分）
  min_hold_time_minutes: 300

  # 最大ポジション保有時間（分）
  max_hold_time_minutes: 600

  # 並列取引用（未実装用のパラメータ）
  # # 取引間の最小待機時間（秒）
  # min_wait_between_trades_seconds: 60

  # # 取引間の最大待機時間（秒）
  # max_wait_between_trades_seconds: 180

  # トレーディングラウンド間のクールダウン時間（秒）
  # 全ポジションクローズ後、次のラウンド開始までの待機時間
  min_cooldown_between_rounds_seconds: 10
  max_cooldown_between_rounds_seconds: 30

  # ウォレット間の取引実行ディレイ（秒）
  # 両建てを同時にやるとbot判定されそうなのでそれを回避するためのディレイ
  wallet_execution_delay: 1

  # レバレッジ倍率
  leverage: 20

  # 最小注文サイズ（USDT建て）
  # 取引所の最小注文要件を満たすため
  minimum_order_size_usdt: 100

# API設定
api_settings:
  # Aster APIのベースURL
  base_url: https://fapi.asterdex.com

  # APIリクエストのタイムアウト時間（秒）
  timeout: 30

  # APIリクエストの最大リトライ回数
  max_retries: 3

# ログ設定
logging:
  # ログレベル（DEBUG, INFO, WARNING, ERROR, CRITICAL）
  log_level: INFO

  # ログファイルの保存先パス
  log_file: logs/trading.log

# Discord通知設定
discord:
  # レポート送信間隔（分）
  report_interval_minutes: 60

  # ポジションオープン時に通知
  send_on_position_open: true

  # ポジションクローズ時に通知
  send_on_position_close: true

  # エラー発生時に通知
  send_on_error: true

  # 残高警告しきい値（USDT）
  low_balance_threshold: 100